### ISSUE TITLE
irace-popuplate doesn't work when --password is provided

### ISSUE THREAD

**Issue by frankivo** [a-tal/irace#2]
Usage:
    irace-populate [options]

**Comment by frankivo** [comment]
This is because I'm an idiot and I should actually use --passwd

**Comment by frankivo** [comment]
I tried to make it give a better error, such as "--password is not a valid option".
Not sure if that is possible with docopt. Found this (old) issue: https://github.com/docopt/docopt/issues/57

**Comment by a-tal** [comment]
I don't mind to change that option, or remove it entirely... I never use it. using the env vars is safer, doesn't leave your password in your process list, shell history, etc...

**Comment by frankivo** [comment]
I tried to use it for debugging. Having a space in front of the command bypasses bash history.
